package com.cse471.project.entity;

public enum LawyerType {
    BUSINESS_LAWYER, BANKRUPTCY_LAWYER, TAX_LAWYER, DEFENSE_LAWYER,
    CONSTITUTIONAL_LAWYER, FAMILY_LAWYER, LABOR_LAWYER, ESTATE_PLANNING_LAWYER,
    IMMIGRATION_LAWYER, PERSONAL_INJURY_LAWYER, INTELLECTUAL_PROPERTY_LAWYER,
    ENTERTAINMENT_LAWYER, MEDICAL_MALPRACTICE_LAWYER, CONTRACT_LAWYER,
    SOCIAL_SECURITY_DISABILITY_LAWYER, GOVERNMENT_LAWYER, MILITARY_LAWYER,
    MERGERS_AND_ACQUISITIONS_LAWYER, ENVIRONMENTAL_LAWYER, REAL_ESTATE_ATTORNEY_OR_PROPERTY_LAWYER,
    TOXIC_TORT_LAWYER, VIDEO_GAME_LAWYER, PUBLIC_INTEREST_LAWYER,
    DIGITAL_MEDIA_AND_INTERNET_LAWYER, FINANCE_AND_SECURITIES_LAWYER,
    CIVIL_RIGHTS_LAWYER, WORKERS_COMPENSATION_LAWYER,
    CIVIL_LITIGATION_LAWYER
}
